import { subscribeOpenAILogging } from "dry-utils-openai";
import { createHash } from "node:crypto";
import type { Context } from "../portal/pTypes.ts";
import type { Bag, NumBag } from "../types.ts";

/**
 * Catches and stores AI telemetry metrics.
 * It uses a hash of scenario details to mark and later find metrics for specific AI calls.
 */
class TelemetryCatcher {
  private logs: Record<string, NumBag> = {};

  constructor() {}

  /**
   * Creates a modified input for a scenario.
   * It adds a unique hash to the input item, which is used to identify the corresponding metrics later.
   * This hash is embedded in the data sent to the LLM.
   * @param key A string key to generate the hash (e.g., scenario name).
   * @param val The original input context or string to modify.
   * @returns A tuple containing the hash and the modified input.
   */
  createMarkedInput(
    key: string,
    val: Context<Bag> | string,
  ): [string, Context<Bag> | string] {
    // Add a simple hash to differentiate parallel requests.
    // This DOES affect what is sent to the LLM, but should be opaque to it.
    const v = this.hash(key);

    if (typeof val === "string") {
      return [v, `[${v}] ${val}`];
    }

    const { item, context } = val;

    return [
      v,
      {
        item: { v, ...item },
        context,
      },
    ];
  }

  /**
   * Stores a metrics entry.
   * The key for storing the metrics is extracted from the input string of the log.
   * This assumes the hash generated by `createMarkedInput` is present at a specific position in the input log.
   * @param tag The tag from the log, expected to contain the hash.
   * @param metrics The metrics to store.
   */
  catch(tag: string, metrics: NumBag): void {
    // The key is the hash embedded in the input string
    // For Context objects this is `{ v: 'hash_value', ... }`
    // For string inputs this is `"[hash_value] rest of string"`
    // This extracts the 8-character hash.
    const key = tag[0] === "{" ? tag.slice(6, 14) : tag.slice(2, 10);
    this.logs[key] = metrics;
  }

  /**
   * Finds metrics associated with a given context.
   * It uses the hash stored in the context's item to look up the metrics.
   * @param v The hash to look for.
   * @returns The found metrics, or undefined if none matches.
   */
  find(v: string): NumBag | undefined {
    return this.logs[v];
  }

  /**
   * Generates a SHA256 hash from the given key and truncates it.
   * @param key The key to include in the hash.
   * @returns An 8-character hexadecimal hash string.
   */
  private hash(key: string): string {
    return createHash("sha256").update(key).digest("hex").slice(0, 8);
  }
}

export const catcher = new TelemetryCatcher();

// Configure AI logging to use the TelemetryCatcher instance.
// This subscribes to logs from AI calls made via dry-utils-openai.
subscribeOpenAILogging({
  log: ({ tag, val }) => console.log(tag, val),
  error: ({ tag, val }) => console.error(new Error(tag, { cause: val })),
  aggregate: ({ dense, metrics }) =>
    catcher.catch(dense["in"] as string, metrics),
});
