name: Refresh Jobs

on:
  schedule:
    # Runs daily around 10:32 PM Pacific
    # Due to GitHub lag, this might not run for hours later
    - cron: "32 22 * * *"
      timezone: "America/Los_Angeles"
  workflow_dispatch:

jobs:
  call_api:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Make API call to trigger job refresh
        env:
          API_URL: ${{ secrets.PROD_API_URL }}/api/refresh/jobs
          API_TOKEN: ${{ secrets.PROD_API_TOKEN }}
        run: |
          curl -X POST "$API_URL" \
          -H "Authorization: Bearer $API_TOKEN" \
          -H "Content-Type: application/json"
